---
# This playbook prints a simple debug message
- name: Echo 
  hosts: "{{class}}"

  tasks:
  - name: Print debug message
    debug:
      msg: "{{text}}"
  - name: Creates directory
    file:
      path: /tmp/sahlovs/java_dns
      state: directory
  - name: download sources
    get_url: url=https://repo1.maven.org/maven2/dnsjava/dnsjava/3.5.0/dnsjava-3.5.0.jar dest=/tmp/sahlovs/java_dns/dnsjava-3.5.0.jar
