
# This playbook prints a simple debug message
- name: Echo 
  hosts: "{{class}}"

  tasks:
  - name: Print debug message
    debug:
      msg: "{{text}}"
  - name: Creates directory
    file:
      path: /tmp/sahlovs/java_dns
      state: directory
